# Generated by Django 4.2.4 on 2023-08-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='desc',
        ),
    ]
